[project]
name = "weibospider-fork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dateutil>=2.9.0.post0",
    "scrapy>=2.12.0",
    "toml>=0.10.2",
]
